/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JFileChooser;

import bodyprogram.Conversion;
import bodyprogram.RecordWindow;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.event.FocusListener;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;

/**
 *Responsible for main view to interact with Nurse
 * @author jacob
 */
public class HSInputWindow extends javax.swing.JFrame {

	

	/**
	 * Creates new form GUI
	 */
	public HSInputWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	private void initComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(6, 28, 86, 14);
		txtPatientName = new javax.swing.JTextField();
		txtPatientName.setBounds(72, 25, 86, 20);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(176, 56, 58, 14);
		txtPatientHeight1 = new javax.swing.JFormattedTextField();
		txtPatientHeight1.setBounds(221, 53, 34, 20);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(6, 56, 58, 14);
		txtPatientWeight = new javax.swing.JFormattedTextField();
		txtPatientWeight.setBounds(54, 53, 33, 20);
		lblPatientHeightUnit1 = new javax.swing.JLabel();
		lblPatientHeightUnit1.setBounds(265, 54, 33, 14);
		txtPatientHeight2 = new javax.swing.JFormattedTextField();
		txtPatientHeight2.setBounds(308, 53, 36, 20);
		lblPatientHeightUnit2 = new javax.swing.JLabel();
		lblPatientHeightUnit2.setBounds(348, 56, 42, 14);
		txtDate = new org.jdesktop.swingx.JXDatePicker();
		txtDate.setBounds(6, 195, 169, 22);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(6, 175, 81, 14);
		btnGenerateReport = new javax.swing.JButton();
		btnGenerateReport.setBounds(220, 195, 182, 23);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(6, 82, 105, 14);
		txtCholesterol = new javax.swing.JFormattedTextField();
		txtCholesterol.setBounds(101, 79, 71, 20);
	

		jLabel6 = new javax.swing.JLabel();
		jLabel6.setBounds(351, 27, 42, 14);
		txtAge = new javax.swing.JFormattedTextField();
		txtAge.setBounds(378, 24, 49, 20);
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setBounds(6, 108, 58, 14);
		txtBMI = new javax.swing.JFormattedTextField();
		txtBMI.setBounds(101, 105, 71, 20);

		jLabel8 = new javax.swing.JLabel();
		jLabel8.setBounds(6, 134, 105, 14);
		txtBloodPressure = new javax.swing.JTextField();
		txtBloodPressure.setBounds(101, 131, 71, 20);

		jMenuBar1 = new javax.swing.JMenuBar();
		btnFileMenu = new javax.swing.JMenu();
		btnOpenFile = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		btnCalculateBMI = new javax.swing.JMenuItem();
		searchByDate = new javax.swing.JMenuItem();
		searchTotalsByDate = new javax.swing.JMenuItem();
		jMenuItem1.setText("jMenuItem1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Heath Screening Evaluation");
		setName("mainGUI"); // NOI18N
		setResizable(false);
	

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Record"));

		jLabel1.setText("First Name:");

		txtPatientName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtPatientName.setName("txtPatientName"); // NOI18N

		jLabel2.setText("Height:");

		txtPatientHeight1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
		txtPatientHeight1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtPatientHeight1.setName("txtPatientHeight"); // NOI18N
		
	

		jLabel3.setText("Weight:");

		txtPatientWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
		txtPatientWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtPatientWeight.setName("txtPatientWeight"); // NOI18N
	

		lblPatientHeightUnit1.setText("feet");
		lblPatientHeightUnit1.setName("lblPatientHeightLeftUnit"); // NOI18N

		txtPatientHeight2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
		txtPatientHeight2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtPatientHeight2.setName("txtPatientHeight2"); // NOI18N
		
	

		lblPatientHeightUnit2.setText("inches");

		jLabel4.setText("Record Date");

		btnGenerateReport.setText("Save and Clear");


		jLabel5.setText("Cholesterol:");

		txtCholesterol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
		txtCholesterol.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		jLabel6.setText("Age:");

		txtAge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
		txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				txtAge_TextChange(evt);
			}
		});

		jLabel7.setText("BMI:");

		txtBMI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
		txtBMI.setHorizontalAlignment(javax.swing.JTextField.CENTER);

		jLabel8.setText("Blood Pressure:");

		txtBloodPressure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
	

		JLabel lblLbs = new JLabel();
		lblLbs.setBounds(91, 56, 20, 14);
		lblLbs.setText("lbs");
		lblLbs.setName("lblPatientHeightLeftUnit");

		txtCholesterolIndicator = new JTextField();
		txtCholesterolIndicator.setBounds(186, 79, 226, 20);
		txtCholesterolIndicator.setEnabled(false);
		txtCholesterolIndicator.setDisabledTextColor(Color.BLACK);
		txtCholesterolIndicator.setColumns(10);

		txtBMIIndicator = new JTextField();
		txtBMIIndicator.setBounds(186, 105, 226, 20);
		txtBMIIndicator.setEnabled(false);
		txtBMIIndicator.setDisabledTextColor(Color.BLACK);
		txtBMIIndicator.setColumns(10);

		txtBloodPressureIndicator = new JTextField();
		txtBloodPressureIndicator.setBounds(186, 131, 226, 20);
		txtBloodPressureIndicator.setEnabled(false);
		txtBloodPressureIndicator.setDisabledTextColor(Color.BLACK);
		txtBloodPressureIndicator.setColumns(10);
		
		JLabel lblLastName = new JLabel();
		lblLastName.setBounds(161, 28, 73, 14);
		lblLastName.setText("Last Name:");
		
		txtPatientNameLast = new JTextField();
		txtPatientNameLast.setHorizontalAlignment(SwingConstants.CENTER);
		txtPatientNameLast.setBounds(230, 25, 111, 20);
		txtPatientNameLast.setColumns(10);

		lblPatientHeightUnit1.getAccessibleContext().setAccessibleName("jLabel4");

		jMenuBar1.setBorder(null);

		btnFileMenu.setText("File");

		btnOpenFile.setText("Open");
		btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOpenFileActionPerformed(evt);
			}
		});
		btnFileMenu.add(btnOpenFile);

		jMenuBar1.add(btnFileMenu);

		jMenu1.setText("Tools");

		btnCalculateBMI.setText("Calculate BMI");
	
		jMenu1.add(btnCalculateBMI);

		jMenu2.setText("Search");
		
		searchByDate.setText("search by date");
		searchTotalsByDate.setText("Search totals by date");


		
		
		jMenu2.add(searchByDate);
		jMenu2.add(searchTotalsByDate);
		
		mnView = new JMenu("View");
		jMenuBar1.add(mnView);
		
		mntmShowPieCharts = new JMenuItem("Show Pie Charts");
		mnView.add(mntmShowPieCharts);

		jMenuBar1.add(jMenu1);
		jMenuBar1.add(jMenu2);
		setJMenuBar(jMenuBar1);

		

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap(19, Short.MAX_VALUE)
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 453, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
		);
		jPanel1.setLayout(null);
		jPanel1.add(jLabel8);
		jPanel1.add(jLabel7);
		jPanel1.add(jLabel5);
		jPanel1.add(txtBloodPressure);
		jPanel1.add(txtBMI);
		jPanel1.add(txtCholesterol);
		jPanel1.add(txtBloodPressureIndicator);
		jPanel1.add(txtBMIIndicator);
		jPanel1.add(txtCholesterolIndicator);
		jPanel1.add(jLabel3);
		jPanel1.add(txtPatientWeight);
		jPanel1.add(lblLbs);
		jPanel1.add(jLabel2);
		jPanel1.add(txtPatientHeight1);
		jPanel1.add(jLabel1);
		jPanel1.add(txtPatientName);
		jPanel1.add(lblLastName);
		jPanel1.add(txtPatientNameLast);
		jPanel1.add(lblPatientHeightUnit1);
		jPanel1.add(txtPatientHeight2);
		jPanel1.add(lblPatientHeightUnit2);
		jPanel1.add(jLabel6);
		jPanel1.add(txtAge);
		jPanel1.add(jLabel4);
		jPanel1.add(txtDate);
		jPanel1.add(btnGenerateReport);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents


	private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOpenFileActionPerformed
		JFileChooser jf = new JFileChooser("Open a patient record");
		jf.showOpenDialog(this);

		if (jf.getSelectedFile() != null) {
			RecordWindow rw = new RecordWindow(RecordWindow.RECORD_OPEN, jf.getSelectedFile().getAbsolutePath());
			rw.setVisible(true);
		}
	}




	
	private void txtAge_TextChange(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtAge_TextChange
		checkAge();
		
	}
	
	private boolean checkAge() {
		String value = txtAge.getText();
		boolean result = true;
		if (!Conversion.IsValidInteger(value, 1, 120)) {
			txtAge.setBackground(Color.PINK);
			result = false;
		} else {
			txtAge.setBackground(Color.WHITE);
		}
		return result;
	}

	
	

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem btnCalculateBMI;
	private javax.swing.JMenuItem searchByDate;
	private javax.swing.JMenuItem searchTotalsByDate;
	private javax.swing.JMenu btnFileMenu;
	private javax.swing.JButton btnGenerateReport;
	private javax.swing.JMenuItem btnOpenFile;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblPatientHeightUnit1;
	private javax.swing.JLabel lblPatientHeightUnit2;
	private javax.swing.JFormattedTextField txtAge;
	private javax.swing.JFormattedTextField txtBMI;
	private javax.swing.JTextField txtBloodPressure;
	private javax.swing.JFormattedTextField txtCholesterol;
	private org.jdesktop.swingx.JXDatePicker txtDate;
	private javax.swing.JFormattedTextField txtPatientHeight1;
	private javax.swing.JFormattedTextField txtPatientHeight2;
	private javax.swing.JTextField txtPatientName;
	private javax.swing.JFormattedTextField txtPatientWeight;
	private JTextField txtCholesterolIndicator;
	private JTextField txtBMIIndicator;
	private JTextField txtBloodPressureIndicator;
	private JMenu mnView;
	private JMenuItem mntmShowPieCharts;
	private JTextField txtPatientNameLast;



	
	
	public String getCholesterolText(){
		
		return txtCholesterol.getText();
	}
	
	public String getName(){
		return txtPatientName.getText().toString();
	}
	
	public void setRiskIndicator(String indicator){
		txtCholesterolIndicator.setText(indicator);
	}
	
	public void setBloodPressureIndicator(String inidcator){
		txtBloodPressureIndicator.setText(inidcator);
	}
	
	public String getBloodPressureText(){
		return txtBloodPressure.getText();
	}
	
	public String getBmiText(){
		return txtBMI.getText();
	}
	
	public void setBmiText(String bmiValue){
		txtBMI.setText(bmiValue);
	}
	public String getWeightText(){
		return txtPatientWeight.getText();
	}
	
	public void setBmiIndicator(String indicator){
		txtBMIIndicator.setText(indicator);
	}
	
	public String getPatientHeightInFeetText(){
		return txtPatientHeight1.getText();
	}
	
	public String getPatientHeightInInchesText(){
		
		return txtPatientHeight2.getText();
	}
	
	
	
	public void setNameField(String name){
		jLabel1.setText(name);
	}

	public void addBloodPressureKeyListener(KeyListener k){
		txtBloodPressure.addKeyListener(k);
		
	}
	
	public void setBloodPressureBackground(Color color){
		txtBloodPressure.setBackground(color);
	}
	
	public void setFeetBackground(Color color){
		txtPatientHeight1.setBackground(color);
	}
	
	public void setInchesBackground(Color color){
		txtPatientHeight2.setBackground(color);
	}
	
	public void addBloodPressureFocusListener(FocusListener f){
		txtBloodPressure.addFocusListener(f);
	}

	public void addCholesteroldFieldFocusListener(FocusListener f){
		txtCholesterol.addFocusListener(f);
	}
	
	public void addNameListener(KeyListener k){
		txtPatientName.addKeyListener(k);
	}
	
	public void addCholesterolFieldKeyListener(KeyListener k){
		txtCholesterol.addKeyListener(k);
	}
	
	public void addBmiKeyListener(KeyListener k){
		txtBMI.addKeyListener(k);
	}
	
	public void addSearchTotalsByDate(ActionListener a){
		searchTotalsByDate.addActionListener(a);
	}
	
	public void addBmiMenuCalculationactionListener(ActionListener a){
		btnCalculateBMI.addActionListener(a);
	}

	public void addBmiFocusListener(FocusListener f){
		txtBMI.addFocusListener(f);
	}
	
	public void addPatientHeightInFeetListener(KeyListener k){
		txtPatientHeight1.addKeyListener(k);
	}
	
	public void addPatientHeightInInchesListener(KeyListener k){
		txtPatientHeight2.addKeyListener(k);
	
	}
	
	public void addWeightListener(KeyListener k){
		txtPatientWeight.addKeyListener(k);
	}
	
	public void addAgeListener(KeyListener k){
		txtAge.addKeyListener(k);
	}
	
	public void addAgeFocusListener(FocusListener f){
		txtAge.addFocusListener(f);
	}
	
	public void addNameFocusListener(FocusListener f){
		txtPatientName.addFocusListener(f);
	}
	
	public String getAgeText(){
		return txtAge.getText();
	}
	
	public void setWeightBackground(Color color){
		txtPatientWeight.setBackground(color);
	}
	
	public void addDatePickerFocusListener(FocusListener f){
		txtDate.addFocusListener(f);
	}
	
	public String getDateText(){
		return txtDate.getDate().toString();
	}
	
	public void addReportButtonActionListener(ActionListener a){
		btnGenerateReport.addActionListener(a);
	}
	

	
	public void addSearchByDateActionListener(ActionListener a){
		searchByDate.addActionListener(a);
	}
	

	
	/**
	 * Reset all fields to start a new record
	 */
	public void clearComponents() {
		txtPatientName.setText("");
		txtPatientNameLast.setText("");
		txtPatientHeight1.setText("");
		txtPatientWeight.setText("");
		txtPatientHeight2.setText("");
		//txtDate.setDate(null);
		txtCholesterol.setText("");
		txtAge.setText("");
		txtBMI.setText("");
		txtBloodPressure.setText("");
		txtBloodPressureIndicator.setText("");
		txtBMIIndicator.setText("");
		txtCholesterolIndicator.setText("");
	}
}
